name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping beast-stl
        run: curl -sf https://beast-stl.rekayasa-sipil.my.id/ || exit 1
